name: Printer
main: com.reliableplugins.printer.Printer
version: 3.0
depend:
  - Vault
softdepend:
  - Citizens
  - SuperiorSkyblock2
  - BentoBox
  - IridiumSkyblock
  - ShopGUIPlus
  - zShop
  - DynamicShop
  - Residence
  - Lands
  - Factions
  - FactionsX
  - ASkyBlock
  - ProtocolLib
  - ClaimHook
author: Reachy
commands:
  printer:
    description: Help command for Printer
    usage: "/printer help"